### ISSUE TITLE
List of countries as Names

### ISSUE THREAD

**Issue by dceejay** [marcellobarile/multilang-sentiment#4]
Hi, would it be possible to list the countries also as country names ?
I can't find names corresponding to the standard two character codes for several in the list - like  
el, eu, ceb, fa, fy, ha, haw, hi, hy, ig, iw, jw, ka, kk, ko, ju, lo, mi... 
thanks

**Comment by dceejay** [comment]
Found this other list - that does in fact have all of them, apart from zh-tw  - which is Chinese (Taiwan)

https://github.com/unicode-cldr/cldr-localenames-modern/blob/master/main/en-GB/languages.json

**Comment by marcellobarile** [comment]
Hello @dceejay ,
sorry for the late reply, somehow I didn't get the notification :\
What you say has totally sense, I'll add the country names as suggested.

Best,
Marcello
